version: '3.3'
services:
  app:
    container_name: EmailService
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/baadmin1/email:/app/logs
    # restart: always